### ISSUE TITLE
Datatable back-end : tri incorrect

### ISSUE THREAD

**Issue by AdrienHalletUCL** [AdrienHalletUCL/HaitiWater#10]
Quand la table a plus de données que l'interface ne peut en afficher, j'ai l'impression que le tri est fait  **après** le filtre des X premiers éléments.

Exemple d'erreur que ça produit : 
La table contient 20 éléments avec les ID 1-20.
La page ne peut en afficher que 10 (par défaut).
Si on trie la colonne "ID" par ordre descendant, le premier ID sera le numéro 10 (descendant jusque 1) alors qu'on devrait avoir le numéro 20 (descendant jusque 11)

**Comment by AdrienHalletUCL** [comment]
Ah, aussi la pagination ne fonctionne plus ? Enfin en bas à droite la sélection de page n'affiche que "1", là par contre je sais pas d'où ça vient

**Comment by CelineDknp** [comment]
Done. Tu fermes l'issue si c'est bon de ton coté ? (La pagination fonctionne chez moi, confirme-moi)

**Comment by AdrienHalletUCL** [comment]
Je check ça demain, merci de la rapidité !

**Comment by AdrienHalletUCL** [comment]
Fonctionne, merci !
